### ISSUE TITLE
logging handler: may raise error on some mac

### ISSUE THREAD

**Issue by wjo1212** [aliyun/aliyun-log-python-sdk#130]
Traceback (most recent call last):
  File "log_test.py", line 5, in <module>
    from aliyun.log import *
  File "/Library/Python/2.7/site-packages/aliyun_log_python_sdk-0.6.45-py2.7.egg/aliyun/log/__init__.py", line 39, in <module>
    from .logger_hanlder import SimpleLogHandler, QueuedLogHandler, LogFields, UwsgiQueuedLogHandler
  File "/Library/Python/2.7/site-packages/aliyun_log_python_sdk-0.6.45-py2.7.egg/aliyun/log/logger_hanlder.py", line 57, in <module>
    BUILTIN_LOG_FIELDS_NAMES.update(set(LogFields[x].value for x in BUILTIN_LOG_FIELDS_NAMES))
  File "/Library/Python/2.7/site-packages/aliyun_log_python_sdk-0.6.45-py2.7.egg/aliyun/log/logger_hanlder.py", line 57, in <genexpr>
    BUILTIN_LOG_FIELDS_NAMES.update(set(LogFields[x].value for x in BUILTIN_LOG_FIELDS_NAMES))
TypeError: 'type' object has no attribute '__getitem__'

root cause:
seems it's using builtin enum which doesn't support [x] operations.

**Comment by sls-dev-agent** [comment]
该 issue 已贴 `Not Reproducible` 标签，且使用环境是 Python 2.7（已于 2020-01-01 EOL，本 SDK 不再支持）。

如在 Python 3.6+ 仍能复现，请重新提 issue 并附上完整环境信息。本 issue 可关闭。
