### ISSUE TITLE
fail to update logtailconfig via json file via CLI

### ISSUE THREAD

**Issue by wjo1212** [aliyun/aliyun-log-python-sdk#63]
```shell
>> aliyun log update_logtail_config --project_name=dlq-test-sls-project1 --config_detail="file://./test1.json" --client-name=beijing
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/aliyun", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aliyunlogcli/cli_core.py", line 148, in main
    ret = getattr(client, method_name)(**args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aliyun/log/logclient.py", line 1205, in update_logtail_config
    resource = "/configs/" + config_detail.config_name
AttributeError: 'SeperatorFileConfigDetail' object has no attribute 'config_name'
```

**Comment by wjo1212** [comment]
fixed in next release
