### ISSUE TITLE
python2.6 support issue

### ISSUE THREAD

**Issue by wjo1212** [aliyun/aliyun-log-python-sdk#69]
1. protobuf latest version doesn't support py2.6 any more, but we could use older version in setup.py
2. other issue found:

```shell
Traceback (most recent call last):
  File "tests/sample.py", line 354, in <module>
    main()
  File "tests/sample.py", line 330, in main
    sample_pull_logs(client, project, logstore)
  File "tests/sample.py", line 53, in sample_pull_logs
    datetime.fromtimestamp(int(time.time() - 60)).strftime('%Y-%m-%d %H:%M:%S'))
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/aliyun/log/logclient.py", line 566, in get_cursor
    params = {'type': 'cursor', 'from': str(start_time) if start_time in ("begin", "end") else parse_timestamp(start_time)}
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/aliyun/log/util.py", line 215, in parse_timestamp
    return int((dt - datetime(1970, 1, 1)).total_seconds())
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'
```

**Comment by wjo1212** [comment]
fixed in 0.6.25
