### ISSUE TITLE
using uwsgi_handler in virtualenv cause some import error

### ISSUE THREAD

**Issue by wjo1212** [aliyun/aliyun-log-python-sdk#83]
it might not be caused by the handler, but the uwsgi module itself.

```python
LOGGING_CONFIG = {
    'version': 1,
    'formatters': {
        'rawformatter': {
            'class': 'logging.Formatter',
            'format': '%(message)s'
        }
    },
    'handlers': {
        'sls_handler': {
            '()': 'aliyun.log.UwsgiQueuedLogHandler',
            'level': 'INFO',
            'formatter': 'rawformatter',

            # custom args:
            'end_point': settings.DATAENTRY_ENDPOINT,
            'access_key_id': base64.b64decode(settings.DATAENTRY_ACCESS_ID),
            'access_key': base64.b64decode(settings.DATAENTRY_ACCESS_KEY),
            'project': app.config["ALIYUN_LOG_PROJECT"],
            'log_store': app.config["ALIYUN_LOG_LOGSTORE"]
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": app.config["LOG_INFO_FILE"],
            "when": "midnight",
            "formatter": "rawformatter",
            "encoding": "utf-8",
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "when": "midnight",
            "filename": app.config["LOG_ERROR_FILE"],
            "formatter": "rawformatter",
            "encoding": "utf-8",
        },
        "console": {
            "level": "NOTSET",
            "class": "logging.StreamHandler",
            "stream": sys.stderr,
            "formatter": "rawformatter"
        }
    },
    'loggers': {
        'sls': {
            'handlers': ['sls_handler', 'file', 'console'],
            'level': 'INFO',
            'propagate': False
        },
        'file': {
            "handlers": ['console', 'file', 'file_error'],
            "level": "DEBUG",
            "propagate": False,
        }
    }
}
```

```shell
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/gelin/antsophon-backend/core/log.py", line 76, in <module>
    logging.config.dictConfig(LOGGING_CONFIG)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler u'sls_handler': No module named uwsgi
```

**Comment by tonywangcn** [comment]
Did you solve it?
