### ISSUE TITLE
function client.list_project does not work

### ISSUE THREAD

**Issue by pugna0** [aliyun/aliyun-log-python-sdk#94]
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    res = client.list_project(offset=-1, size=100)
  File "/Users/pugna/venv/test/lib/python2.7/site-packages/aliyun/log/logclient.py", line 2445, in list_project
    return ListProjectResponse(resp, header)
  File "/Users/pugna/venv/test/lib/python2.7/site-packages/aliyun/log/project_response.py", line 82, in __init__
    self.count = int(resp['count'])
KeyError: 'count

And any chat-rooms for developers ? ^_^

**Comment by wjo1212** [comment]
你好，
offset不能为-1的，你如果想要拿所有，可以配置为size=-1。

顺便问下你连的是哪一个region？似乎应该报错这样的错误：{"errorCode": "ParameterInvalid", "errorMessage": "offset : -1 pair is invalid", "requestId": "......"}

另外，欢迎加入日志服务用户钉钉群：11775223
